# ============================================================
# LAB 3 - VULNERABLE: Secrets Expuestos como Variables de Entorno
# ============================================================
# ⚠ PROBLEMA: Credenciales en base64 (NO cifrado),
#   expuestas como env vars visibles con 'env' o /proc.
# ============================================================
apiVersion: v1
kind: Namespace
metadata:
  name: lab3-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: lab3-secrets
type: Opaque
data:
  DB_HOST: cG9zdGdyZXMuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==  # postgres.default.svc.cluster.local
  DB_USER: YWRtaW4=                                              # admin
  DB_PASSWORD: U3VwM3JTZWNyZXRQQHNzdzByZCEyMDI0             # Sup3rSecretP@ssw0rd!2024
  DB_NAME: cHJvZHVjdGlvbl9kYg==                                 # production_db
---
apiVersion: v1
kind: Pod
metadata:
  name: app-with-secrets
  namespace: lab3-secrets
spec:
  containers:
    - name: app
      image: nginx:1.25
      envFrom:
        - secretRef:
            name: db-credentials    # ⚠ TODAS las keys como env vars
      # ⚠ Sin securityContext
