###############################################
# LAB 4 — UNIDAD 4: ServiceAccounts
# Archivo: lab4-serviceaccount.yaml
#
# Crea dos ServiceAccounts con diferentes niveles
# de acceso:
#   - dev-reader:  solo puede LEER (get, list, watch)
#   - dev-deployer: puede LEER y CREAR recursos
#
# Un ServiceAccount es la identidad de un Pod
# dentro del cluster. Determina QUE puede hacer
# el Pod en la API de Kubernetes.
#
# Despliegue (requiere namespace):
#   kubectl apply -f lab4-serviceaccount.yaml
#   kubectl get sa -n lab-rbac
#
# Limpiar:
#   kubectl delete -f lab4-serviceaccount.yaml
###############################################

# ═══════════════════════════════════════════
# ServiceAccount: dev-reader
# Identidad para Pods que SOLO necesitan leer
# (monitoreo, dashboards, logs)
# ═══════════════════════════════════════════
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-reader
  namespace: lab-rbac
  labels:
    role: reader
    lab: unidad4-lab4
---
# ═══════════════════════════════════════════
# ServiceAccount: dev-deployer
# Identidad para Pods que necesitan crear
# y gestionar recursos (CI/CD, operators)
# ═══════════════════════════════════════════
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-deployer
  namespace: lab-rbac
  labels:
    role: deployer
    lab: unidad4-lab4
