# ============================================================
# LAB 2 - VULNERABLE: RBAC Excesivo (cluster-admin a SA)
# ============================================================
# ⚠ PROBLEMA: Se otorga cluster-admin a un ServiceAccount,
#   dando acceso total al clúster desde cualquier Pod.
# ============================================================
apiVersion: v1
kind: Namespace
metadata:
  name: lab2-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: overprivileged-sa
  namespace: lab2-rbac
---
# ⚠ PELIGRO: ClusterRoleBinding con cluster-admin
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: overprivileged-sa
    namespace: lab2-rbac
roleRef:
  kind: ClusterRole
  name: cluster-admin          # ⚠ ACCESO TOTAL AL CLÚSTER
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: attacker-pod
  namespace: lab2-rbac
spec:
  serviceAccountName: overprivileged-sa  # ⚠ SA con cluster-admin
  containers:
    - name: attacker
      image: bitnami/kubectl:1.28
      command: ["sleep", "infinity"]
